# Builds the Betaflight firmware
#
# After building, artifacts are released to a seperate repository.
#
# Azure Pipelines requires the following extensions to be installed:
# - GitHub Tool: https://marketplace.visualstudio.com/items?itemName=marcelo-formentao.github-tools
#
# You'll also need to setup the follwing pipeline variables: 
#     "releaseNotes" - This is used to add the release notes in the windows job in the build stage so they can be published as part of the github release in the release stage
#     "endpoint" - The name of the github endpoint link setup in AzDo - setup when linking AzDo and GitHub
#     "owner" - The owner of the repository to release to e.g. betaflight
#     "repoName" - The name of the repository to release to e.g. betaflight-configurator-nightly


variables:
  owner: derdanu
  repoName: betaflight-akramode
  releaseNotes: This is a build of a akramode enabled release tag. It may be unstable and result in corrupted configurations or data loss. **Use only for testing.**

name: $(Build.RequestedFor)_$(Build.SourceBranchName)_$(BuildID)

trigger: none

stages:
- stage: Build
  jobs:
  - job: 'Linux'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: git clone https://github.com/betaflight/betaflight.git
      displayName: 'Cloning Betaflight Sourcecode'
    - script: cd betaflight; git checkout tags/$(version) -b $(version).patch
      displayName: 'Target Version $(version)'
    - script: cd betaflight; make arm_sdk_install
      displayName: 'Install the build toolchain'
    - script: cd betaflight; git apply ../$(version).patch
      displayName: 'Patching Akramode'
    - script: cd betaflight; make unified
      displayName: 'Build Unified Targets'
      condition: ge(variables['version'], '4.2.0')
    - script: cd betaflight; make all
      displayName: 'Build All Targets'
      condition: lt(variables['version'], '4.2.0')      
    - script: cd betaflight; mkdir release; cp obj/*.hex release/
      displayName: 'Copy artefacts'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Linux release'
      inputs: 
        artifactName: betaflight
        targetPath: '$(System.DefaultWorkingDirectory)/betaflight/release/'

- stage: Release
  jobs:
  - job: Release

    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        targetPath: '$(Pipeline.Workspace)'
    - powershell: Write-Output ("##vso[task.setvariable variable=today;]$(Get-Date -Format yyyyMMdd)")
    - task: GitHubReleasePublish@1
      inputs:
        githubEndpoint: '$(endpoint)'
        manuallySetRepository: true
        githubOwner: '$(owner)'
        githubRepositoryName: '$(repoName)'
        githubTag: $(version)
        githubReleaseTitle: '$(version)'
        githubReleaseNotes: |+
          $(releaseNotes)
        githubReleaseDraft: false
        githubReleasePrerelease: false
        githubIgnoreAssets: false
        githubReleaseAsset: |
          $(Pipeline.Workspace)/betaflight/**
        githubReuseRelease: true
        githubReuseDraftOnly: false
        githubSkipDuplicatedAssets: false
        githubEditRelease: true
        githubDeleteEmptyTag: false
